<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rbt_pendulum" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="mass1" value="0.8" /> <!-- mass of Link 1 -->
	<xacro:property name="mass2" value="1.0" /> <!-- mass of Link 2 -->
	<xacro:property name="mass3" value="1.2" /> <!-- mass of Link 3 -->
	<xacro:property name="mass4" value="0.3" /> <!-- mass of Link 4 -->
	<xacro:property name="length1" value="2.5" /> <!-- Length of Link 1 -->
	<xacro:property name="length2" value="1.5" /> <!-- Length of Link 2 -->
	<xacro:property name="length3" value="1.8" /> <!-- Length of Link 3 -->
	<xacro:property name="length4" value="0.8" /> <!-- Length of Link 4 -->
	<xacro:property name="rod_radius" value="0.05" /> <!-- Same radius for all rod links -->

  <!-- Run Gazebo-specific initialization -->
  <xacro:include filename="$(find rbt_pendulum)/urdf/rbt_pendulum.gazebo" />

	<!-- Import Rviz colors -->
	<xacro:include filename="$(find rbt_pendulum)/urdf/materials.xacro" />

	<link name="world"/>

    <joint name="fixed" type="fixed">
    	<parent link="world"/>
    	<child link="link1"/>
  	</joint>





  	<link name="link1">
  		<collision>
  			<origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
  			<geometry>
  				<cylinder length="${length1}" radius="${rod_radius}" />
  			</geometry>
  		</collision>

  		<visual>
  			<origin xyz="0 0 ${length1/2}" rpy="0 0 0"/>
  			<geometry>
  				<cylinder length="${length1}" radius="${rod_radius}" />
  			</geometry>
  			<material name="orange"/>
  		</visual>

  		<inertial>
  			<origin xyz="0 0 ${-length1/2}" rpy="0 0 0"/>
  			<mass value="${mass1}"/>
  			<inertia
  				ixx="${mass1 / 12.0 * (length1*length1 + 3*rod_radius*rod_radius)}" ixy="0.0" ixz="0.0"
  				iyy="${mass1 / 12.0 * (length1*length1 + 3*rod_radius*rod_radius)}" iyz="0.0"
  				izz="${mass1 / 12.0 * (6*rod_radius*rod_radius)}"/>
  		</inertial>
  	</link>





  	<joint name="joint1" type="continuous">
    	<parent link="link1"/>
    	<child link="link2"/>
    	<origin xyz="0 0 ${length1}" rpy="0 0 0"/>
    	<axis xyz="0 1 0"/>
    	<dynamics damping="0.7"/>
  	</joint>




  	<link name="link2">
  		<collision>
  			<origin xyz="0 ${2*rod_radius} ${length2/2}" rpy="0 0 0"/>
  			<geometry>
  				<cylinder length="${length2}" radius="${rod_radius}" />
  			</geometry>
  		</collision>

  		<visual>
  			<origin xyz="0 ${2*rod_radius} ${length2/2}" rpy="0 0 0"/>
  			<geometry>
  				<cylinder length="${length2}" radius="${rod_radius}" />
  			</geometry>
  			<material name="red"/>
  		</visual>

  		<inertial>
  			<origin xyz="0 ${2*rod_radius} ${length2/2}" rpy="0 0 0"/>
  			<mass value="${mass2}"/>
  			<inertia
  				ixx="${mass2 / 12.0 * (length2*length2 + 3*rod_radius*rod_radius)}" ixy="0.0" ixz="0.0"
  				iyy="${mass2 / 12.0 * (length2*length2 + 3*rod_radius*rod_radius)}" iyz="0.0"
  				izz="${mass2 / 12.0 * (6*rod_radius*rod_radius)}"/>
  		</inertial>
  	</link>





    <transmission name="simple_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint1">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="joint1">
        <mechanicalReduction>5</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>




  	

</robot>
