controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hiqp_controller:
      type: hiqp_ros/HiqpController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController


hiqp_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    command_joints:
      - joint1
      - joint2
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: velocity
