main3: main3.cpp
	g++ main3.cpp -o main3 -lcasadi -I/usr/local/include/eigen3 -std=c++11

main2: main2.cpp
	g++ main2.cpp -o main2 -lcasadi -I/usr/local/include/eigen3 -std=c++11

main: main.cpp
	g++ main.cpp -o main -lcasadi -I/usr/local/include/eigen3 -std=c++11