two_arm_gripper:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50  
  hiqp_joint_velocity_controller:
    type: hiqp_ros/HiQPJointVelocityController
    #sampling_time: 1.0 # ms, this has been deprecated
    visualization_publish_rate: 50 #Hz
    joints:
      - joint_left1_to_body_top
    task_monitoring:
      active: 1
      publish_rate: 50.0 # Hz
