two_arm_gripper:
  hiqp_joint_velocity_controller:
     #hiqp_preload_jnt_limits:
     # - link_frame: yumi_link_1_r
     #   limitations: [1.4835, -2.94, 2.94, 1.0] #dq_max, lower joint limit, upper joint limit, dynamics gain

     #hiqp_preload_geometric_primitives:
     # - name: floor_avoidance_plane
     #   type: plane 
     #   frame_id: yumi_body
     #   visible: true
     #   color: [0.5, 0.5, 0.5, 1.0]
     #   parameters: [0.0, 0.0, 1.0, 0.02]

     #hiqp_preload_tasks:
     # - name: yumi_link_5_l_floor_avoidance
     #   priority: 2
     #   visible: true
     #   active: true
     #   monitored: false
     #   def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_link_5_l_avoidance_sphere > floor_avoidance_plane']
     #   dyn_params: ['TDynLinear', '10.0']